name: gcp-service-catalog crawl

# Triggered manually via the "Run workflow" button
on:
  schedule:
    - cron: 0 11 * * *
  workflow_dispatch:

jobs:
  crawl:
    runs-on: arc-runner-set
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    timeout-minutes: 20

    environment: crawl
    concurrency:
      group: crawl

    permissions:
      contents: "write"
      id-token: "write"
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.0' # GOVERSION

      - name: Build gcp-service-catalog
        run: |
          go build -o gcp-service-catalog main.go

      - id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: "access_token"
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_USER }}
          access_token_lifetime: "1200s"

      - name: Delete services.json file
        run: |
          rm -rf services.json
          rm -rf directory.json

      - name: Run gcp-service-catalog with crawl parameter
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=${{steps.auth.outputs.credentials_file_path}}
          ./gcp-service-catalog -crawl

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add services.json
          git add directory.json
          git commit -m "Updated on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Update the remote URL to include the token for authentication
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          # Push the changes to the branch that tr
          git push origin HEAD:${{ github.ref }}
